name: Lint Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
    - name: Download Source Code
      uses: actions/checkout@v3

    - name: Set up the Node.JS Runtime
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Clean Install Dependencies
      run: npm ci

    - name: Lint the project
      run: npm run-script lint
