name: Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Download Source Code
      uses: actions/checkout@v4

    - name: Set up the Node.JS Runtime
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Clean Install Dependencies
      run: npm ci
      
    - name: Build Project
      run: npm run-script build

    - name: Run the Unit Tests
      run: npm run-script test
